# Form implementation generated from reading ui file 'LoginForm.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import pymysql
from PyQt6 import QtCore, QtGui, QtWidgets
from page1 import Ui_MainWin


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("MainWin")
        Form.resize(730, 513)
        Form.setStyleSheet("border : 2px solid black;\n"
"")
        self.Username_lbl = QtWidgets.QLabel(parent=Form)
        self.Username_lbl.setGeometry(QtCore.QRect(40, 110, 151, 61))
        self.Username_lbl.setObjectName("Username_lbl")
        self.Passwd_lbl = QtWidgets.QLabel(parent=Form)
        self.Passwd_lbl.setGeometry(QtCore.QRect(40, 240, 141, 41))
        self.Passwd_lbl.setObjectName("Passwd_lbl")
        self.Login_lbl = QtWidgets.QLabel(parent=Form)
        self.Login_lbl.setGeometry(QtCore.QRect(280, 0, 121, 51))
        self.Login_lbl.setObjectName("Login_lbl")
        self.Username_lnedit = QtWidgets.QLineEdit(parent=Form)
        self.Username_lnedit.setGeometry(QtCore.QRect(220, 130, 421, 31))
        self.Username_lnedit.setObjectName("Username_lnedit")
        self.Passwd_lnedit = QtWidgets.QLineEdit(parent=Form)
        self.Passwd_lnedit.setGeometry(QtCore.QRect(220, 240, 421, 31))
        self.Passwd_lnedit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.Passwd_lnedit.setObjectName("Passwd_lnedit")
        self.Submit_PushBtn = QtWidgets.QPushButton(parent=Form)
        self.Submit_PushBtn.setGeometry(QtCore.QRect(60, 327, 201, 41))
        self.Submit_PushBtn.setStyleSheet("background-color : blue;\n"
"color: white\n"
"")
        self.Submit_PushBtn.setObjectName("Submit_PushBtn")
        self.Submit_PushBtn.clicked.connect(self.sub_data)
        self.Clear_PushBtn = QtWidgets.QPushButton(parent=Form)
        self.Clear_PushBtn.setGeometry(QtCore.QRect(410, 330, 211, 41))
        self.Clear_PushBtn.setStyleSheet("background-color : black;\n"
"color : white")
        self.Clear_PushBtn.setObjectName("Clear_PushBtn")
        self.Submit_PushBtn.clicked.connect(self.clear_data)
        self.ErrorBox_lbl = QtWidgets.QLabel(parent=Form)
        self.ErrorBox_lbl.setGeometry(QtCore.QRect(30, 420, 671, 41))
        self.ErrorBox_lbl.setText("")
        self.ErrorBox_lbl.setObjectName("ErrorBox_lbl")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def sub_data(self):
        username = self.Username_lnedit.text().strip()
        password = self.Passwd_lnedit.text().strip()
        if len(username) == 0 or len(password) == 0:
            self.ErrorBox_lbl.setText('Check Your Input')
        else:
             import pymysql as conn
             db_conn = pymysql.connect(
                 user='root',
                 password='',
                 host='localhost',
                 database='app_db'
             )
             cur = db_conn.cursor()

             # Query to fetch user details based on username and password
             log_query = f'''SELECT username,password from reg_tbl
                         WHERE {'username'} like username
                         and {'password'} like password
             '''
             cur.execute(log_query)
             result = cur.fetchone()

             if result == None:
                 self.ErrorBox_lbl.setText('Inorrect Username And Password')
             else:
                 from PyQt6.QtWidgets import QMainWindow
                 self.main = QMainWindow()
                 self.win = Ui_MainWin()
                 self.win.setupUi(self.main)
                 self.main.show()

             db_conn.commit()
             cur.close()
             db_conn.close()

    def clear_data(self):
        self.Username_lnedit.clear()
        self.Passwd_lnedit.clear()





    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "LoginForm"))
        self.Username_lbl.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">UserName</span></p></body></html>"))
        self.Passwd_lbl.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">PassWord</span></p></body></html>"))
        self.Login_lbl.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">LOGIN</span></p></body></html>"))
        self.Submit_PushBtn.setText(_translate("Form", "Submit"))
        self.Clear_PushBtn.setText(_translate("Form", "Clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
