# Form implementation generated from reading ui file 'SimpleInterest.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from datetime import datetime

class Ui_MainWin(object):
    def setupUi(self, MainWin):
        MainWin.setObjectName("MainWin")
        MainWin.resize(1073, 719)
        self.centralwidget = QtWidgets.QWidget(parent=MainWin)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(310, 20, 641, 631))
        self.widget.setStyleSheet("border : 1px solid green;\n"
"")
        self.widget.setObjectName("widget")
        self.SI_lbl = QtWidgets.QLabel(parent=self.widget)
        self.SI_lbl.setGeometry(QtCore.QRect(100, 10, 421, 31))
        self.SI_lbl.setStyleSheet("border : 0px solid balck;")
        self.SI_lbl.setObjectName("SI_lbl")
        self.Welcome_lbl = QtWidgets.QLabel(parent=self.widget)
        self.Welcome_lbl.setGeometry(QtCore.QRect(20, 50, 291, 31))
        self.Welcome_lbl.setStyleSheet("border : 1px solid balck;")
        self.Welcome_lbl.setObjectName("Welcome_lbl")
        self.Greeting_lbl = QtWidgets.QLabel(parent=self.widget)
        self.Greeting_lbl.setGeometry(QtCore.QRect(40, 90, 291, 31))
        self.Greeting_lbl.setStyleSheet("border : 1px solid balck;")
        self.Greeting_lbl.setObjectName("Greeting_lbl")
        self.Time_lbl = QtWidgets.QLabel(parent=self.widget)
        self.Time_lbl.setGeometry(QtCore.QRect(140, 130, 151, 31))
        self.Time_lbl.setStyleSheet("border : 1px solid balck;")
        self.Time_lbl.setObjectName("Time_lbl")
        self.ErrorBox_lbl = QtWidgets.QLabel(parent=self.widget)
        self.ErrorBox_lbl.setGeometry(QtCore.QRect(60, 570, 531, 51))
        self.ErrorBox_lbl.setText("")
        self.ErrorBox_lbl.setObjectName("ErrorBox_lbl")
        self.PAmt_lbl = QtWidgets.QLabel(parent=self.widget)
        self.PAmt_lbl.setGeometry(QtCore.QRect(30, 240, 191, 41))
        self.PAmt_lbl.setStyleSheet("border : 0px solid black;")
        self.PAmt_lbl.setObjectName("PAmt_lbl")
        self.Interest_lbl = QtWidgets.QLabel(parent=self.widget)
        self.Interest_lbl.setGeometry(QtCore.QRect(30, 289, 191, 31))
        self.Interest_lbl.setStyleSheet("border : 0px solid black;")
        self.Interest_lbl.setObjectName("Interest_lbl")
        self.Ptime_lbl = QtWidgets.QLabel(parent=self.widget)
        self.Ptime_lbl.setGeometry(QtCore.QRect(30, 329, 191, 31))
        self.Ptime_lbl.setStyleSheet("border : 0px solid black;")
        self.Ptime_lbl.setObjectName("Ptime_lbl")
        self.Result_lbl = QtWidgets.QLabel(parent=self.widget)
        self.Result_lbl.setGeometry(QtCore.QRect(30, 450, 181, 31))
        self.Result_lbl.setStyleSheet("border : 0px solid black;")
        self.Result_lbl.setObjectName("Result_lbl")
        self.PAmt_lnedit = QtWidgets.QLineEdit(parent=self.widget)
        self.PAmt_lnedit.setGeometry(QtCore.QRect(270, 250, 221, 31))
        self.PAmt_lnedit.setObjectName("PAmt_lnedit")
        self.Interest_lnedit = QtWidgets.QLineEdit(parent=self.widget)
        self.Interest_lnedit.setGeometry(QtCore.QRect(270, 290, 221, 31))
        self.Interest_lnedit.setObjectName("Interest_lnedit")
        self.Ptime_lnedit = QtWidgets.QLineEdit(parent=self.widget)
        self.Ptime_lnedit.setGeometry(QtCore.QRect(270, 330, 221, 31))
        self.Ptime_lnedit.setObjectName("Ptime_lnedit")
        self.Result_lnedit = QtWidgets.QLineEdit(parent=self.widget)
        self.Result_lnedit.setGeometry(QtCore.QRect(270, 440, 221, 31))
        self.Result_lnedit.setObjectName("Result_lnedit")
        self.CalSI_PushBtn = QtWidgets.QPushButton(parent=self.widget)
        self.CalSI_PushBtn.setGeometry(QtCore.QRect(140, 400, 301, 28))
        self.CalSI_PushBtn.setObjectName("CalSI_PushBtn")
        self.CalSI_PushBtn.clicked.connect(self.calculate_si)
        self.Submit_PushBtn = QtWidgets.QPushButton(parent=self.widget)
        self.Submit_PushBtn.setGeometry(QtCore.QRect(110, 520, 121, 31))
        self.Submit_PushBtn.setObjectName("Submit_PushBtn")
        self.Submit_PushBtn.clicked.connect(self.submit)
        self.Clear_PushBtn = QtWidgets.QPushButton(parent=self.widget)
        self.Clear_PushBtn.setGeometry(QtCore.QRect(420, 520, 121, 31))
        self.Clear_PushBtn.setObjectName("Clear_PushBtn")
        self.Clear_PushBtn.clicked.connect(self.clear)
        self.Back_PushBtn = QtWidgets.QPushButton(self.widget)
        self.Back_PushBtn.setGeometry(QtCore.QRect(270, 520, 121, 31))
        self.Back_PushBtn.setObjectName("Back_PushBtn")
        self.Back_PushBtn.setVisible(True)
        self.Back_PushBtn.clicked.connect(MainWin.close)
        MainWin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1073, 26))
        self.menubar.setObjectName("menubar")
        MainWin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWin)
        self.statusbar.setObjectName("statusbar")
        MainWin.setStatusBar(self.statusbar)

        self.retranslateUi(MainWin)
        QtCore.QMetaObject.connectSlotsByName(MainWin)

        self.updateTimeAndGreeting()

    def updateTimeAndGreeting(self):
        current_time = datetime.now()
        new_time = current_time.strftime('%I:%M:%p')  # 12hr format with am/pm
        self.Time_lbl.setText(new_time)
        if current_time.hour < 12:
            greeting = 'Good Morning'
        else:
            greeting = 'Good Afternoon'

        self.Greeting_lbl.setText(greeting)

    def calculate_si(self):
        principal_text = self.PAmt_lnedit.text().strip()
        rate_text = self.Interest_lnedit.text().strip()
        time_text = self.Ptime_lnedit.text().strip()

        if principal_text and rate_text and time_text:
            try:
                principal = float(principal_text)
                rate = float(rate_text)
                time = float(time_text)

                simple_interest = (principal * rate * time) / 100
                self.Result_lnedit.setText(f"{simple_interest:.2f}")
                self.ErrorBox_lbl.setText((f"Simple Interest calculated: {simple_interest:.2f}"))
            except ValueError:
                self.ErrorBox_lbl.setText("Please enter valid numeric values.")
        else:
            self.ErrorBox_lbl.setText("Please enter all fields.")

            db_conn = pymysql.connect(
                user='root',
                password='',
                host='localhost',
                database='app_db'
            )
            cur = db_conn.cursor()

            insert_query = ("INSERT INTO Simple interest_tbl (Principal_Amount, Interest, Time, Result) "
                            "VALUES (%s, %s, %s, %s)")
            cur.execute(insert_query, (principal, rate, time, simple_interest))
            db_conn.commit()



    def submit(self):
        self.ErrorBox_lbl.setText("Data Submitted!")

    def clear(self):
        self.PAmt_lnedit.clear()
        self.Interest_lnedit.clear()
        self.Ptime_lnedit.clear()
        self.Result_lnedit.clear()
        self.ErrorBox_lbl.clear()

    def retranslateUi(self, MainWin):
        _translate = QtCore.QCoreApplication.translate
        MainWin.setWindowTitle(_translate("MainWin", "MainWindow"))
        self.SI_lbl.setText(_translate("MainWin", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">SIMPLE INTEREST</span></p></body></html>"))
        self.Welcome_lbl.setText(_translate("MainWin",'Welcome BigBaby' "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.Greeting_lbl.setText(_translate("MainWin", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.Time_lbl.setText(_translate("MainWin", "<html><head/><body><p align=\"center\"><br/></p><p align=\"center\"><br/></p><p align=\"center\"><br/></p></body></html>"))
        self.PAmt_lbl.setText(_translate("MainWin", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">PRINCIPAL AMOUNT</span></p></body></html>"))
        self.Interest_lbl.setText(_translate("MainWin", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">INTEREST</span></p></body></html>"))
        self.Ptime_lbl.setText(_translate("MainWin", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">TIME</span></p></body></html>"))
        self.Result_lbl.setText(_translate("MainWin", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">RESULT</span></p></body></html>"))
        self.CalSI_PushBtn.setText(_translate("MainWin", "CALCULATE SIMPLE INTEREST"))
        self.Submit_PushBtn.setText(_translate("MainWin", "SUBMIT"))
        self.Clear_PushBtn.setText(_translate("MainWin", "CLEAR"))
        self.Back_PushBtn.setText(_translate("MainWin", "BACK"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWin = QtWidgets.QMainWindow()
    ui = Ui_MainWin()
    ui.setupUi(MainWin)
    MainWin.show()
    sys.exit(app.exec())
