# Form implementation generated from reading ui file 'To-do.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from datetime import datetime


class Ui_MainWin(object):
    def setupUi(self, MainWin):
        MainWin.setObjectName("MainWin")
        MainWin.resize(1142, 760)
        self.centralwidget = QtWidgets.QWidget(parent=MainWin)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(290, 50, 771, 571))
        self.widget.setStyleSheet("border : 1px solid grey;\n"
"background-color: sky blue;\n"
"color: black")
        self.widget.setObjectName("widget")
        self.Todo_lbl = QtWidgets.QLabel(parent=self.widget)
        self.Todo_lbl.setGeometry(QtCore.QRect(114, 20, 551, 31))
        self.Todo_lbl.setStyleSheet("border : 0px solid black;")
        self.Todo_lbl.setObjectName("Todo_lbl")
        self.Welcome_lbl = QtWidgets.QLabel(parent=self.widget)
        self.Welcome_lbl.setGeometry(QtCore.QRect(40, 80, 231, 31))
        self.Welcome_lbl.setStyleSheet("border : 1px solid black;")
        self.Welcome_lbl.setObjectName("Welcome_lbl")
        self.Greeting_lbl = QtWidgets.QLabel(parent=self.widget)
        self.Greeting_lbl.setGeometry(QtCore.QRect(400, 80, 251, 31))
        self.Greeting_lbl.setStyleSheet("border : 1px solid black;")
        self.Greeting_lbl.setObjectName("Greeting_lbl")
        self.Time_lbl = QtWidgets.QLabel(parent=self.widget)
        self.Time_lbl.setGeometry(QtCore.QRect(240, 130, 211, 31))
        self.Time_lbl.setStyleSheet("border : 1px solid black;")
        self.Time_lbl.setObjectName("Time_lbl")
        self.ErrorBox_lbl = QtWidgets.QLabel(parent=self.widget)
        self.ErrorBox_lbl.setGeometry(QtCore.QRect(50, 500, 681, 51))
        self.ErrorBox_lbl.setText("")
        self.ErrorBox_lbl.setObjectName("ErrorBox_lbl")
        self.Submit_PushBtn = QtWidgets.QPushButton(parent=self.widget)
        self.Submit_PushBtn.setGeometry(QtCore.QRect(100, 440, 161, 41))
        self.Submit_PushBtn.setObjectName("Submit_PushBtn")
        self.Submit_PushBtn.clicked.connect(self.submit)
        self.Clear_PushBtn = QtWidgets.QPushButton(parent=self.widget)
        self.Clear_PushBtn.setGeometry(QtCore.QRect(300, 440, 161, 41))
        self.Clear_PushBtn.setObjectName("Clear_PushBtn")
        self.Clear_PushBtn.clicked.connect(self.clear)
        self.Back_PushBtn = QtWidgets.QPushButton(parent=self.widget)
        self.Back_PushBtn.setGeometry(QtCore.QRect(500, 440, 75, 41))
        self.Back_PushBtn.setObjectName("Back_PushBtn")
        self.Back_PushBtn.clicked.connect(MainWin.close)
        self.Shopping_PushBtn = QtWidgets.QPushButton(parent=self.widget)
        self.Shopping_PushBtn.setGeometry(QtCore.QRect(70, 200, 161, 28))
        self.Shopping_PushBtn.setObjectName("Shopping_PushBtn")
        self.Shopping_PushBtn.clicked.connect(self.shopping)
        self.Games_PushBtn = QtWidgets.QPushButton(parent=self.widget)
        self.Games_PushBtn.setGeometry(QtCore.QRect(250, 240, 171, 28))
        self.Games_PushBtn.setObjectName("Games_PushBtn")
        self.Games_PushBtn.clicked.connect(self.games)
        self.Movies_PushBtn = QtWidgets.QPushButton(parent=self.widget)
        self.Movies_PushBtn.setGeometry(QtCore.QRect(450, 200, 171, 28))
        self.Movies_PushBtn.setObjectName("Movies_PushBtn")
        self.Movies_PushBtn.clicked.connect(self.movies)
        self.Saloon_PushBtn = QtWidgets.QPushButton(parent=self.widget)
        self.Saloon_PushBtn.setGeometry(QtCore.QRect(82, 320, 161, 28))
        self.Saloon_PushBtn.setObjectName("Saloon_PushBtn")
        self.Saloon_PushBtn.clicked.connect(self.saloon)
        self.Gym_PushBtn = QtWidgets.QPushButton(parent=self.widget)
        self.Gym_PushBtn.setGeometry(QtCore.QRect(440, 320, 191, 28))
        self.Gym_PushBtn.setObjectName("Gym_PushBtn")
        self.Gym_PushBtn.clicked.connect(self.gym)
        self.Sleep_PushBtn = QtWidgets.QPushButton(parent=self.widget)
        self.Sleep_PushBtn.setGeometry(QtCore.QRect(250, 370, 191, 28))
        self.Sleep_PushBtn.setObjectName("Sleep_PushBtn")
        self.Sleep_PushBtn.clicked.connect(self.sleep)
        MainWin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1142, 26))
        self.menubar.setObjectName("menubar")
        MainWin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWin)
        self.statusbar.setObjectName("statusbar")
        MainWin.setStatusBar(self.statusbar)

        self.retranslateUi(MainWin)
        QtCore.QMetaObject.connectSlotsByName(MainWin)

        self.updateTimeAndGreeting()

    def updateTimeAndGreeting(self):
            current_time = datetime.now()
            new_time = current_time.strftime('%I:%M:%p')  # 12hr format with am/pm
            self.Time_lbl.setText(new_time)
            if current_time.hour < 12:
                greeting = 'Good Morning'
            else:
                greeting = 'Good Afternoon'

            self.Greeting_lbl.setText(greeting)

    def submit(self):
        self.ErrorBox_lbl.setText("Submitted!")

    def clear(self):
        self.ErrorBox_lbl.setText("Cleared!")

    def shopping(self):
        self.ErrorBox_lbl.setText("Go Shopping!")

    def games(self):
        self.ErrorBox_lbl.setText("Play Games!")

    def movies(self):
        self.ErrorBox_lbl.setText("Watch Movies!")

    def saloon(self):
        self.ErrorBox_lbl.setText("Go to the Saloon!")

    def gym(self):
        self.ErrorBox_lbl.setText("Go to the Gym!")

    def sleep(self):
        self.ErrorBox_lbl.setText("Go to Sleep!")



    def retranslateUi(self, MainWin):
        _translate = QtCore.QCoreApplication.translate
        MainWin.setWindowTitle(_translate("MainWin", "MainWindow"))
        self.Todo_lbl.setText(_translate("MainWin", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">TO-DO LIST</span></p></body></html>"))
        self.Welcome_lbl.setText(_translate("MainWin", 'Welcome BigBaby'"<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.Greeting_lbl.setText(_translate("MainWin", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.Time_lbl.setText(_translate("MainWin", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.Submit_PushBtn.setText(_translate("MainWin", "SUBMIT"))
        self.Clear_PushBtn.setText(_translate("MainWin", "CLEAR"))
        self.Back_PushBtn.setText(_translate("MainWin", "BACK"))
        self.Shopping_PushBtn.setText(_translate("MainWin", "GO SHOPPING"))
        self.Games_PushBtn.setText(_translate("MainWin", "PLAY GAMES"))
        self.Movies_PushBtn.setText(_translate("MainWin", "WATCH MOVIES"))
        self.Saloon_PushBtn.setText(_translate("MainWin", "GO TO THE SALOON"))
        self.Gym_PushBtn.setText(_translate("MainWin", "GYM"))
        self.Sleep_PushBtn.setText(_translate("MainWin", "SLEEP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWin = QtWidgets.QMainWindow()
    ui = Ui_MainWin()
    ui.setupUi(MainWin)
    MainWin.show()
    sys.exit(app.exec())
